// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: allen_blink.proto

#ifndef PROTOBUF_allen_5fblink_2eproto__INCLUDED
#define PROTOBUF_allen_5fblink_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_allen_5fblink_2eproto();
void protobuf_AssignDesc_allen_5fblink_2eproto();
void protobuf_ShutdownFile_allen_5fblink_2eproto();

class Blink;
class Yaw;

// ===================================================================

class Blink : public ::google::protobuf::Message {
 public:
  Blink();
  virtual ~Blink();

  Blink(const Blink& from);

  inline Blink& operator=(const Blink& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Blink& default_instance();

  void Swap(Blink* other);

  // implements Message ----------------------------------------------

  Blink* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Blink& from);
  void MergeFrom(const Blink& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double ears = 1;
  inline int ears_size() const;
  inline void clear_ears();
  static const int kEarsFieldNumber = 1;
  inline double ears(int index) const;
  inline void set_ears(int index, double value);
  inline void add_ears(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      ears() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_ears();

  // repeated int32 blink_idx = 2;
  inline int blink_idx_size() const;
  inline void clear_blink_idx();
  static const int kBlinkIdxFieldNumber = 2;
  inline ::google::protobuf::int32 blink_idx(int index) const;
  inline void set_blink_idx(int index, ::google::protobuf::int32 value);
  inline void add_blink_idx(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      blink_idx() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_blink_idx();

  // optional int32 blink_num = 3;
  inline bool has_blink_num() const;
  inline void clear_blink_num();
  static const int kBlinkNumFieldNumber = 3;
  inline ::google::protobuf::int32 blink_num() const;
  inline void set_blink_num(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Blink)
 private:
  inline void set_has_blink_num();
  inline void clear_has_blink_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< double > ears_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > blink_idx_;
  ::google::protobuf::int32 blink_num_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_allen_5fblink_2eproto();
  friend void protobuf_AssignDesc_allen_5fblink_2eproto();
  friend void protobuf_ShutdownFile_allen_5fblink_2eproto();

  void InitAsDefaultInstance();
  static Blink* default_instance_;
};
// -------------------------------------------------------------------

class Yaw : public ::google::protobuf::Message {
 public:
  Yaw();
  virtual ~Yaw();

  Yaw(const Yaw& from);

  inline Yaw& operator=(const Yaw& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Yaw& default_instance();

  void Swap(Yaw* other);

  // implements Message ----------------------------------------------

  Yaw* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Yaw& from);
  void MergeFrom(const Yaw& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double ears = 1;
  inline int ears_size() const;
  inline void clear_ears();
  static const int kEarsFieldNumber = 1;
  inline double ears(int index) const;
  inline void set_ears(int index, double value);
  inline void add_ears(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      ears() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_ears();

  // repeated int32 yaw_idx = 2;
  inline int yaw_idx_size() const;
  inline void clear_yaw_idx();
  static const int kYawIdxFieldNumber = 2;
  inline ::google::protobuf::int32 yaw_idx(int index) const;
  inline void set_yaw_idx(int index, ::google::protobuf::int32 value);
  inline void add_yaw_idx(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      yaw_idx() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_yaw_idx();

  // optional int32 yaw_num = 3;
  inline bool has_yaw_num() const;
  inline void clear_yaw_num();
  static const int kYawNumFieldNumber = 3;
  inline ::google::protobuf::int32 yaw_num() const;
  inline void set_yaw_num(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Yaw)
 private:
  inline void set_has_yaw_num();
  inline void clear_has_yaw_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< double > ears_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > yaw_idx_;
  ::google::protobuf::int32 yaw_num_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_allen_5fblink_2eproto();
  friend void protobuf_AssignDesc_allen_5fblink_2eproto();
  friend void protobuf_ShutdownFile_allen_5fblink_2eproto();

  void InitAsDefaultInstance();
  static Yaw* default_instance_;
};
// ===================================================================


// ===================================================================

// Blink

// repeated double ears = 1;
inline int Blink::ears_size() const {
  return ears_.size();
}
inline void Blink::clear_ears() {
  ears_.Clear();
}
inline double Blink::ears(int index) const {
  return ears_.Get(index);
}
inline void Blink::set_ears(int index, double value) {
  ears_.Set(index, value);
}
inline void Blink::add_ears(double value) {
  ears_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
Blink::ears() const {
  return ears_;
}
inline ::google::protobuf::RepeatedField< double >*
Blink::mutable_ears() {
  return &ears_;
}

// repeated int32 blink_idx = 2;
inline int Blink::blink_idx_size() const {
  return blink_idx_.size();
}
inline void Blink::clear_blink_idx() {
  blink_idx_.Clear();
}
inline ::google::protobuf::int32 Blink::blink_idx(int index) const {
  return blink_idx_.Get(index);
}
inline void Blink::set_blink_idx(int index, ::google::protobuf::int32 value) {
  blink_idx_.Set(index, value);
}
inline void Blink::add_blink_idx(::google::protobuf::int32 value) {
  blink_idx_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Blink::blink_idx() const {
  return blink_idx_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Blink::mutable_blink_idx() {
  return &blink_idx_;
}

// optional int32 blink_num = 3;
inline bool Blink::has_blink_num() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Blink::set_has_blink_num() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Blink::clear_has_blink_num() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Blink::clear_blink_num() {
  blink_num_ = 0;
  clear_has_blink_num();
}
inline ::google::protobuf::int32 Blink::blink_num() const {
  return blink_num_;
}
inline void Blink::set_blink_num(::google::protobuf::int32 value) {
  set_has_blink_num();
  blink_num_ = value;
}

// -------------------------------------------------------------------

// Yaw

// repeated double ears = 1;
inline int Yaw::ears_size() const {
  return ears_.size();
}
inline void Yaw::clear_ears() {
  ears_.Clear();
}
inline double Yaw::ears(int index) const {
  return ears_.Get(index);
}
inline void Yaw::set_ears(int index, double value) {
  ears_.Set(index, value);
}
inline void Yaw::add_ears(double value) {
  ears_.Add(value);
}
inline const ::google::protobuf::RepeatedField< double >&
Yaw::ears() const {
  return ears_;
}
inline ::google::protobuf::RepeatedField< double >*
Yaw::mutable_ears() {
  return &ears_;
}

// repeated int32 yaw_idx = 2;
inline int Yaw::yaw_idx_size() const {
  return yaw_idx_.size();
}
inline void Yaw::clear_yaw_idx() {
  yaw_idx_.Clear();
}
inline ::google::protobuf::int32 Yaw::yaw_idx(int index) const {
  return yaw_idx_.Get(index);
}
inline void Yaw::set_yaw_idx(int index, ::google::protobuf::int32 value) {
  yaw_idx_.Set(index, value);
}
inline void Yaw::add_yaw_idx(::google::protobuf::int32 value) {
  yaw_idx_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Yaw::yaw_idx() const {
  return yaw_idx_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Yaw::mutable_yaw_idx() {
  return &yaw_idx_;
}

// optional int32 yaw_num = 3;
inline bool Yaw::has_yaw_num() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Yaw::set_has_yaw_num() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Yaw::clear_has_yaw_num() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Yaw::clear_yaw_num() {
  yaw_num_ = 0;
  clear_has_yaw_num();
}
inline ::google::protobuf::int32 Yaw::yaw_num() const {
  return yaw_num_;
}
inline void Yaw::set_yaw_num(::google::protobuf::int32 value) {
  set_has_yaw_num();
  yaw_num_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_allen_5fblink_2eproto__INCLUDED
